### ISSUE TITLE
Task1

### ISSUE THREAD

**Issue by ala-n** [imashkanov/EducationalPractice#1]
Задание исполнено верно и зачтено.
Есть только небольшой вопрос к названию репозитория, ибо в дальнейшем, как предпологалось, он же будет использован для всей учебной практики.
Доп. задание (по желанию): заранее почитайте про Pull Requests, ветки (создание/переключение) и теги (на идеально) в git. Имеется ввиду только базовые понятия.

**Comment by imashkanov** [comment]
я понял, хорошо, спасибо :)

**Comment by imashkanov** [comment]
Репозиторий переименован в более правильное общее название - EducationalPractice
Спасибо за рекомендацию.
